### ISSUE TITLE
Error route 

### ISSUE THREAD

**Issue by Faqihyugos** [njinlabs/njinattend-mobile#2]
#ask

Uncaught Error
<img width="482" alt="Screenshot 2023-10-06 at 11 08 13" src="https://github.com/njinlabs/njinattend-mobile/assets/32142762/6ea75ec7-f2d4-431e-beb0-eaaeb5cc4164">

Multiple files match the route name "./(root)/_layout".

error tersebut saya coba saat run expo web, karna saat run android tidak keluar error di expo nya.

mau nanya apakah harus ada yg diubah?

Terimakasih

**Comment by akbaraditamasp** [comment]
Untuk saat ini memang ga ada versi webnya. Hanya setup untuk android & ios. Serta pastikan menggunakan expo sdk terbaru
